Add TL files
ncsu-geoforall-lab/gis714-2023-tangible-landscape pull request #1
Opened 2023-03-21 17:24 UTC by rlwcomposto

These files can be used to find lakes in the tangible landscape (TL) using the elevation in the tangible landscape. When the TL is manipulated, these files can be run and the updated lakes will be shown in the TL. The function came from the GRASS GIS wikipage - https://grasswiki.osgeo.org/wiki/Using_GRASS_GIS_through_Python_and_tangible_interfaces_(workshop_at_FOSS4G_NA_2016)#Tangible_Landscape.

2023-03-22 20:17 UTC, rlwcomposto commented on activities/RC_TL_v2.json
> +        ["d.rast", "map=slope"]
Thank you for catching that, made the change!

2023-03-23 14:02 UTC, petrasovaa commented
Congrats, the checks succeeded! Now try to use your geospatial creativity to customize the copied example. For example:
* display the source point (make it into vector first)
* set the water level dynamically as 50th or 75th percentile of the elevation range
* dynamically find the lowest spot and spread water from there
* something else

2023-04-10 16:20 UTC, petrasovaa requested changes
See my last comment.

2023-04-12 20:49 UTC, rlwcomposto commented
Hi Anna, sorry for the delay, I didn't realize a change was requested and what that entailed. I just added a little flair to the code  (some colors and rivers). 

I'm running into some consistent errors in the tests that I haven't been able to fix yet.

2023-04-12 20:56 UTC, petrasovaa commented
> Hi Anna, sorry for the delay, I didn't realize a change was requested and what that entailed. I just added a little flair to the code (some colors and rivers).
> 
No worries, I think we could do a quick Tangible Landscape session next week.

> I'm running into some consistent errors in the tests that I haven't been able to fix yet.

The relevant error shows incorrect parameter names:

```
ERROR: r.stream.extract: Sorry, <output> is not a valid parameter
ERROR: r.stream.extract: Sorry, <coordinates> is not a valid parameter
ERROR: Required parameter <threshold> not set:
	(Minimum flow accumulation for streams)
```

2023-04-13 18:27 UTC, rlwcomposto commented
Changes are complete, the map should display lakes and rivers at the same time in blue.

2023-04-13 18:54 UTC, rlwcomposto commented
Mistakenly closed pull request, opening so the code can be reviewed.

2023-04-14 13:40 UTC, petrasovaa approved these changes

2023-04-14 13:41 UTC, merged