EmmaButzlerTangibleLandscapes
ncsu-geoforall-lab/gis714-2023-tangible-landscape pull request #2
Opened 2023-03-22 17:20 UTC by 18ebutzler1

2023-03-27 19:26 UTC, petrasovaa requested changes

2023-03-27 19:26 UTC, petrasovaa commented on activities/Emma_Butzler.json
> +        ["d.rast", "map=slope"]
You are not displaying any of the layers you are computing.

2023-03-27 19:26 UTC, petrasovaa commented on activities/Emma_Butzler.json
> +      "instructions": "Change topography and observe changes in contours,curvature, Relief, Fill and Direction."
Please fix the uppercase/lowercase and missing space.

2023-03-27 19:26 UTC, petrasovaa commented on activities/Emma_Butzler.py
> +    )
Not sure what you wanted to show here, but to actually see something useful, display the depressions, not the depressionless DEM or direction.

2023-03-30 20:57 UTC, 18ebutzler1 commented
@petrasovaa i think i addressed all your comment.

2023-03-31 13:36 UTC, petrasovaa commented on activities/Emma_Butzler.py
> +    )
I don't think this was addressed. The output of r.fill.dir is the DEM without the depressions, but it makes sense visually to show the depression themselves. You can derive the depressions by subtracting the two DEMs.

2023-03-31 13:42 UTC, petrasovaa commented on Helloworld
> +
Please also remove this file.

2023-04-05 19:41 UTC, 18ebutzler1 commented
@petrasovaa let me know if the current .py and .json need changed

2023-04-10 16:19 UTC, petrasovaa approved these changes

2023-04-10 16:20 UTC, merged